### ISSUE TITLE
Frage: Datenpunkt umgezogen, wie werte erhalten

### ISSUE THREAD

**Issue by DerDoubleD** [iobroker-community-adapters/ioBroker.statistics#100]
Hallo

Ein Wert den ich in statistics mitlogge ist von `javascript.0.Stromzaehler.Zaehlerstand` umgezogen nach `0_userdata.0.Stromzaehler.Zaehlerstand`

Kann ich die historischen Werte von einem zum anderen Datenpunkt mitnehmen???

Danke & Gruß

**Comment by Apollon77** [comment]
Statistics speichern im eigenen Namespace statistics.0.* diese Zwischendaten ... man müsste dort passend zum neuen Namen die daten quasi manuell kopieren und objekte manuell anlegen
