### ISSUE TITLE
Using Ping Adapter I get massive number of warnings: State value to set for "statistics.0.temp.timeCount.ping.0.192_168_178_27.last" has to be type "number" but received type "boolean" 

### ISSUE THREAD

**Issue by peterimnetz** [iobroker-community-adapters/ioBroker.statistics#101]
When using statistics 1.0.9 for datapoints created by ping adapter my logs are flooded with warnings like

> State value to set for "statistics.0.temp.timeCount.ping.0.192_168_178_27.last" has to be type "number" but received type "boolean" 

Datapoints as created by ping adapter are boolean:

![grafik](https://user-images.githubusercontent.com/54081914/153766279-bf59d6bd-284c-42c9-b29d-9c51d6ed53f7.png)

Generated statistics are working fine but these massive ammount of warnings are quite disturbing. Is it be possible to avoid these warnings using a specific type conversion in implementation of statistic adapter when using boolean?

**Comment by Apollon77** [comment]
Please provide a debug log

**Comment by peterimnetz** [comment]
Please find logfile (debug level) attached
[log.txt](https://github.com/iobroker-community-adapters/ioBroker.statistics/files/8333144/log.txt)
d

**Comment by Apollon77** [comment]
Will be fixed in next version. you maybe neednto delete the objects told in the error messgae (*.last) once. they shozld be recreated - else adjust the objects to have common.type = "mixed" as value
