### ISSUE TITLE
Question: Activate statistics for an object programmatically by JavaScript

### ISSUE THREAD

**Issue by uwe72** [iobroker-community-adapters/ioBroker.statistics#122]
<img width="173" alt="image" src="https://user-images.githubusercontent.com/61848539/173194526-9853882a-2fd9-430c-bf90-0244076ce504.png">

Is there a way to activate statistics for an object programmatically by JavaScript?

**Comment by klein0r** [comment]
See https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#setobject

e.g.

```javascript
const objId = '0_userdata.0.blabla';
let obj = getObject(objId);

if (!obj.common.custom) {
  obj.common.custom = {};
}

obj.common.custom['statistics.0'] = {
  "enabled": true,
  "count": true,
  "sumCount": true,
  "timeCount": false,
  "fiveMin": true,
  "impUnitPerImpulse": 1,
  "impUnit": "W",
  "avg": false,
  "minmax": false,
  "sumDelta": false,
  "sumIgnoreMinus": false,
  "groupFactor": 0.001,
  "logName": "Pulse",
  "sumGroup": "Strom"
};

setObject(objId, obj);
```

**Comment by uwe72** [comment]
I tried like this:


```
const objId = 'shelly.0.SHPLG2-1#49FE33#1.online';
let obj = getObject(objId);

if (!obj.common.custom) {
  obj.common.custom = {};
}

obj.common.custom['statistics.0'] = {
  "enabled": true,
  "count": false,
  "sumCount": false,
  "timeCount": true,
  "fiveMin": false,
  "impUnitPerImpulse": 1,
  "impUnit": "",
  "avg": false,
  "minmax": false,
  "sumDelta": false,
  "sumIgnoreMinus": false,
  "groupFactor": 1,
  "logName": "online_script_trockner"
};

setObject(objId, obj);

```


But i got an error. I guess this is related to the fact that i am using TypeScript. Do you have an idea what i can change?

`javascript.1 (486) script.js.common.Berechnungen.Test_Statistics: TypeScript compilation failed: setObject(objId, obj); ^ ERROR: Argument of type '{ common: { [x: string]: any; [x: number]: any; }; type: "state" \| "channel" \| "folder" \| "device"; acl: { object: number; state: number; owner: string; ownerGroup: string; }; _id: string; native: { [x: string]: any; }; enums: { ...; }; from: string; user: string; ts: number; }' is not assignable to parameter of type '(Omit<StateObject, "acl" \| "_id"> & { _id?: string; acl?: StateACL; }) \| (Omit<InstanceObject, "acl" \| "_id"> & { _id?: string; acl?: ObjectACL; }) \| ... 10 more ... \| (Omit<...> & { ...; })'. Type '{ common: { [x: string]: any; [x: number]: any; }; type: "state" \| "channel" \| "folder" \| "device"; acl: { object: number; state: number; owner: string; ownerGroup: string; }; _id: string; native: { [x: string]: any; }; enums: { ...; }; from: string; user: string; ts: number; }' is not assignable to type 'Omit<OtherObject, "acl" \| "_id"> & { _id?: string; acl?: ObjectACL; }'. Type '{ common: { [x: string]: any; [x: number]: any; }; type: "state" \| "channel" \| "folder" \| "device"; acl: { object: number; state: number; owner: string; ownerGroup: string; }; _id: string; native: { [x: string]: any; }; enums: { ...; }; from: string; user: string; ts: number; }' is not assignable to type 'Omit<OtherObject, "acl" \| "_id">'. Types of property 'common' are incompatible. Property 'name' is missing in type '{ [x: string]: any; [x: number]: any; }' but required in type 'OtherCommon'.`


<img width="661" alt="image" src="https://user-images.githubusercontent.com/61848539/185614339-9e74637d-e134-4d22-b707-9395ae8b5496.png">

**Comment by uwe72** [comment]
;-) I know that this would work, but i want to use typescript. I have scripts (arrays) in global packages, all in typescript. Within the script - i have the problems now - i want to have access to this global scripts, written in typescript.

**Comment by uwe72** [comment]
But i think this problem is not related to the statistic adapter, thats why i created a question ticket in iobroker forum.
