### ISSUE TITLE
More or adjustable decimal places

### ISSUE THREAD

**Issue by Walkinlarge2010** [iobroker-community-adapters/ioBroker.statistics#123]
Implementation of more decimal places (currently three) or variable configuration of decimal places in the adapter

**Comment by klein0r** [comment]
I can just increase the value. How many do you need?
The "problem" is, that all calculated values are rounded to 5 digits. That can lead to strange results if the factor is too small...

**Comment by Walkinlarge2010** [comment]
Thanks for the fast reply. I think 5 digits are for my use cases enough. Maybe you can add this to the adapter settings, I doesn’t know what’s the fastest and best way to change it. 
With the option to change it in the settings, everyone can use it to the own needs. 

Best Regards
Walkinlarge2010

**Comment by klein0r** [comment]
5 digits will lead to issues. Lets say you configure 0,27€/kWh and enable impulses to groups.
When u use 0,00001 kWh per pulse, 1 * 0,00001 * 0,27 = 0,0000027 (7 digits). Which will be rounded to 5 digits afterwards and the result confuses the user.

Why do you nee so many digits? What is the use case?

**Comment by Walkinlarge2010** [comment]
Sorry for the late reply. But this problem you have also with 3 or 4 digits. More digits will help to get better accuracy in the results. On this example you'll have always this problem.

I need more digits in the result, because I make calculations with the 15Min results and have to distribute the 15min value to 4 different datapoints. If the 15 Min is for example 0,007 kWh and I have to distribute this to 4 datapoints with different shares, it has a big inaccuracy. With more digits I can reduce this problem.

This is the reason why more digits would make sense for me and my use case :)

**Comment by klein0r** [comment]
> But this problem you have also with 3 or 4 digits.

How? Please add a calculation in with an example for 3 digits and a result rounded to 5 digits.

**Comment by Walkinlarge2010** [comment]
I mean that's a floating problem

...
4 Digits: 1*0,0001*0,27=0,000027 rounded to 4 Digits = 0,0000
3 Digits: 1*0,001*0,27=0,00027 rounded to 3 Digits = 0,000
...

For this reason, I cannot understand your concerns about the curious results

**Comment by klein0r** [comment]
> 3 Digits: 1 * 0,001 * 0,27=0,00027 rounded to 3 Digits = 0,000

Exactly. As already mentioned: The digits in the configuration are limited to 3, because the result of each calculation is rounded to 5 digits. If we increase the number of digits for the configuration, we have to increase the number of rounded digits in the results, too.

https://github.com/iobroker-community-adapters/ioBroker.statistics/blob/159db22d2620433303c7a0aee15cbe006ef014a0/main.js#L7

**Comment by Walkinlarge2010** [comment]
Ok, I think I got it :)

If we increase the Digits in the configuration, we have also to increase the digits in the results. Is the is problem or a big thing? If it is, I have to make a workaround on my self

**Comment by klein0r** [comment]
Can you explain your current calculation and the issue again? Why do you need more digits on the **configuration** page?

**Comment by Walkinlarge2010** [comment]
I just saw that I already have 5 decimal places in the result for the 15min values. Probably I was wrong, or was that already changed with an update.

Therefore we can close the request. Sorry.

**Comment by klein0r** [comment]
Mh, maybe my first answer wasn't clear enough 😄 

And yes, I've updated the precision from 4 to 5 digits in version 2.1.0

**Comment by Walkinlarge2010** [comment]
Thx 🙏
