### ISSUE TITLE
Ignoriere Null-Werte für numerische Datenpunkte

### ISSUE THREAD

**Issue by petterpet** [iobroker-community-adapters/ioBroker.statistics#128]
**Describe the bug**  
Ich möchte von numerischen Datenpunkten den Durchschnitt sowie Min- & Max-Werte haben. Vor jeder Aktualisierung der Datenpunkte werden diese jedoch auf Null gesetzt. Somit ist der Min-Wert immer Null und auch der Durchschnitt verfälscht.

**To Reproduce**  
Dies ist bei den Spritpreisen des Tankerkönig-Adapters der Fall.

**Expected behavior**  
Ich wünsche mir einen Haken (Checkbox), mit der man aktivieren kann, dass Null-Werte ignoriert werden.

Im konkreten Fall mit dem Tankerkönig-Adapter kann der Spritpreis nun mal nie Null werden.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/41487271/179966655-3a653932-0755-4197-a15d-fdf625290cae.png)
![image](https://user-images.githubusercontent.com/41487271/179967178-6e750786-0b75-47d5-8dc2-1a35995b6911.png)

**Versions:**  
 - Adapter version: 2.1.1

**Comment by klein0r** [comment]
Auf ``null`` (deleteState) oder auf ``0``? Numerisch 0 kann ich ja schlecht ignorieren

**Comment by petterpet** [comment]
Numerische 0

Wieso kann man das nicht ignorieren?

**Comment by klein0r** [comment]
Weil es tausende Beispiele gibt, wo 0 sinnvoll wäre. Außentemperatur z.B.

**Comment by petterpet** [comment]
> Weil es tausende Beispiele gibt, wo 0 sinnvoll wäre. Außentemperatur z.B.

Korrekt. Deshalb möchte ich ja auch nicht, dass die 0 immer ignoriert wird.
Sondern eine Checkbox, mit der dies bei Bedarf aktiviert werden kann.


> Ich würde im Tankerkönig-Adapter diese Einstellung entfernen um das Verhalten zu umgehen.

Beeinflusst das den Tankerkönig nicht negativ? Denn soweit ich mich erinnern kann ist der Haken im default gesetzt.

**Comment by klein0r** [comment]
> Beeinflusst das den Tankerkönig nicht negativ?

Soweit ich weiß geht es nur darum, dass man so vermeiden möchte, dass "alte Werte" stehen bleiben, wenn der Dienst nicht verfügbar ist. Besser wäre es, wenn der Tankerkönig Adapter die Werte löschen würde (deleteState). ODER es müsste mit dem ``q``-Flag gearbeitet werden. Da könnte man wirklich drüber sprechen, dass nur ``state.q == 0`` vom statistics Adapter berücksichtigt wird.

Meiner Meinung nach versucht der Issue hier ein Problem zu beheben, welches ein anderer Adapter verursacht. Wenn der 0 als gültigen Wert schreibt, dann sollte man damit auch arbeiten dürfen.

**Comment by petterpet** [comment]
> Meiner Meinung nach versucht der Issue hier ein Problem zu beheben, welches ein anderer Adapter verursacht. Wenn der 0 als gültigen Wert schreibt, dann sollte man damit auch arbeiten dürfen.

Naja, in den Datenbank-Adaptern gibt es die angefragte Checkbox "Ignoriere Null-Werte" auch.
Die Implementierung des q-Flags in beiden Adaptern wäre meiner Meinung nach die sauberste Lösung.

> Ich würde den Haken entfernen und das Problem ist gelöst.
Werde ich machen. Da nur die billigsten Werte resettet werden, glaube ich auch nicht mehr das so viel schiefgehen kann. Danke  für das Codesnipsel.

**Comment by klein0r** [comment]
Ach, lustig. Sorry ich habe nicht auf die Namen geachtet 😄
