### ISSUE TITLE
Values in tmp / sumDelta wrong

### ISSUE THREAD

**Issue by mattenausohz** [iobroker-community-adapters/ioBroker.statistics#134]
The adapter was working fine for like three weeks. Today I found my consumption for day, month, quarter, week and year suddenly slightly the all same at around 19200 - 19400 kwh. Values for 15min and hour seem consistent and correct (hour is 0,4 kwh). 

 - Adapter version: 2.1.1
 - JS-Controller version: 4.0.23
 - Node version: 18.6.0
 - Operating system: raspbian

**Comment by klein0r** [comment]
Please provide more information what’s wrong and what is expected. Add a screenshot for explanation

**Comment by mattenausohz** [comment]
Können wir das auf deutsch machen?

Mittlerweile habe ich angeblich heute 25721,365kWh verbraucht, was natürlich vollkommen falsch ist. Ich liege im Schnitt pro Tag insgesamt bei 5 - 8 kWh. Interessant ist, dass der Wert für "day" identisch ist mit "week". Aber auch ein wöchentlicher Stromverbrauch von 25721 kWh wäre natürlich vollkommen falsch.
<img width="1269" alt="Bildschirm­foto 2022-08-08 um 21 47 51" src="https://user-images.githubusercontent.com/31960356/183502516-a417af89-0d39-4b44-ad77-ba8779871028.png">

**Comment by mattenausohz** [comment]
So sieht es heute morgen aus
<img width="1282" alt="Bildschirm­foto 2022-08-09 um 08 08 46" src="https://user-images.githubusercontent.com/31960356/183576968-7ffecbcd-dbcb-4315-8977-4a3ceffefe01.png">
:

**Comment by klein0r** [comment]
Und auf welchem Datenpunkt basieren die Werte? Ein Zählerstand, welcher ständig hochzählt?
Und der springt nicht ab und zu mal auf 0?

**Comment by mattenausohz** [comment]
Ja genau. Ein Zählerstand, der nur hoch zählt, direkt vom digitalen Stromzähler ausgelesen.

**Comment by mattenausohz** [comment]
Ok, bei Uptime steht 1 Tag und 12 Stunden. Kann es damit zu tun haben?

<img width="1197" alt="Bildschirm­foto 2022-08-09 um 18 44 17" src="https://user-images.githubusercontent.com/31960356/183709520-1634a0ec-b703-46f9-8d69-816fcb5acbea.png">

**Comment by klein0r** [comment]
Interessant wäre, ob es Ausreißer gibt oder ob der Wert immer sauber hochzählt.

**Comment by mattenausohz** [comment]
Ich hab jetzt mal einen SQL Server drangehängt. Gibt's einen Tipp was ich jetzt erstmal machen kann?

**Comment by klein0r** [comment]
Gibts schon Erkenntnisse?

**Comment by klein0r** [comment]
Ich hatte ein ähnliches Phänomen. Nachdem ich mehrere Tests geschrieben habe, kann das passieren, wenn mehrere Aufgaben parallel verarbeitet werden. Also wenn sich der State sehr schnell nacheinander geändert hat. Das habe ich nun behoben, indem ich den kompletten Adapter auf links gezogen habe, damit alles schön nacheinander bearbeitet wird.

Bitte mit Version 2.3.0 testen, welche ich gleich freigebe
