### ISSUE TITLE
avg folder shows minmax values

### ISSUE THREAD

**Issue by DrkVrdng** [iobroker-community-adapters/ioBroker.statistics#147]
I would expect average values within the AVG folder.
But I see 3 values: dayAvg (that's what I expect), dayMin and dayMax (this should be shown within minmax folder).
Instead of dayMin and dayMax I would expect further average values, e.g. hourAvg, WeekAvg, monthAvg, yearAvg, ...

**Comment by klein0r** [comment]
Duplicate of #43
