### ISSUE TITLE
Frage: Falschen Wert korrigieren

### ISSUE THREAD

**Issue by DerDoubleD** [iobroker-community-adapters/ioBroker.statistics#150]
**Describe the bug**  
Durch einen Scriptfehler habe ich in der Statistic einen Falschen wert.
Kann ich diesen manuell korrigieren

**To Reproduce**  
...

**Expected behavior**  
Der überwachte Datenpunkt wurde versehentlich mit einem falschem Wert beschrieben. Dadurch ist der durch den Adapter berechnete Wert natürlich falsch. Kann ich den Fehler manuell beheben? 

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/47006370/199923527-050dbd73-6726-4f80-a68e-fe8fe29e0339.png)

**Versions:**  
 - Adapter version: aktuell
 - JS-Controller version: aktuell
 - Node version: aktuell
 - Operating system:  debian

**Additional context**  
...

**Comment by klein0r** [comment]
- Instanz stoppen
- Werte ändern
- Instanz wieder starten
