### ISSUE TITLE
rate_per_time_unit = inf

### ISSUE THREAD

**Issue by duffy6** [iobroker-community-adapters/ioBroker.statistics#153]
Hallo zusammen,

leider zeigt mir rate_per_time_unit den Wert "inf" an.
Es geht um einen Zählerwert eines Stromzählers. Ist es ein Bug oder hab ich einen Denkfehler?

![Unbenannt](https://user-images.githubusercontent.com/30000750/208636171-c8788e30-8dbd-44c0-8cd2-dfbb878c253f.PNG)

**Comment by klein0r** [comment]
Was genau hat die Frage mit dem statistics Adapter zu tun

**Comment by duffy6** [comment]
Sorry, falscher Repository. Muss der Vorweihnachtstsress sein
