### ISSUE TITLE
Decreasing values should be also calculated

### ISSUE THREAD

**Issue by lxffm** [iobroker-community-adapters/ioBroker.statistics#162]
**Is your feature request related to a problem? Please describe.**
Currently my actor is reporting an oiltank filling with obviously decreasing values. But this not calculated correctly in the e.g. delta calculation, as the consecutive measurement will be lower than the present one

**Describe the solution you'd like**
Please also correctly calculate decreasing values, where the e.g. filling of an oiltank is correctly considered.

**Describe alternatives you've considered**

**Additional context**

**Comment by klein0r** [comment]
Decreasing values are possible and are supported (if you don't check "Ignore errors / Ignores difference if new value less than old one").
