### ISSUE TITLE
Problems with update to 2.3.0 

### ISSUE THREAD

**Issue by marios774** [iobroker-community-adapters/ioBroker.statistics#177]
Nach dem Update bleibt der Adapter rot.
Hier die Fehlermeldung des Logs.

`host.deb11iobroker | 2023-04-04 07:58:26.246 | error | startInstance system.adapter.statistics.0 Adapter dependency not fulfilled on any host: required adapter "admin" has wrong version. Installed "5.3.1", required ">=5.3.2"!`

Node.js: v16.19.0(16.20.0)
NPM: 8.19.3(8.19.4)
Admin: 6.3.5 ???

**Comment by klein0r** [comment]
Was ist die Frage?

**Comment by marios774** [comment]
Also die Frage ist, weshalb kommt es zu der Fehlermeldung? 
NodeJS sollte passen und der Admin ist auf v6, trotzdem kommt die Meldung und der Adapter klappt leider nicht mehr.

**Comment by mcm1957** [comment]
Bei mir alles OK, statistics 2.3.0, admin 6.3.7
Der Fehler sieht aber eher nach admin / js-controlelr Problem aus, zumindst kommt die Fehlermeldung nicht aus dem Adapter.
