### ISSUE TITLE
SumDelta -> Week consumption is not calculated correctly

### ISSUE THREAD

**Issue by TomasiDeveloping** [iobroker-community-adapters/ioBroker.statistics#178]
**Describe the bug**  
SumDelta weeks consumption is not calculated correctly. As it looks it is calculated like the day.
Yesterday Wednesday it had the same value as day and this morning it is back to 0.

**To Reproduce**  
1. Go to 'statistics -> temp -> sumDelta -> Week'

**Expected behavior**  
Correct calculation as in the old version of the adapter

**Screenshots & Logfiles**  
<img width="957" alt="2023-04-05 20_36_12-objects - ioBroker" src="https://user-images.githubusercontent.com/67390491/230275481-6fd69b05-c920-4b6f-968e-d1bde793ba83.png">
![2023-04-06 06_46_25-objects - ioBroker](https://user-images.githubusercontent.com/67390491/230275518-ce4200cc-fdc8-473d-b638-5ae8a0265695.png)

**Versions:**  
 - Adapter version: v2.3.0
 - JS-Controller version: 4.0.24
 - Node version: v16.19.0
 - Operating system: linux

**Additional context**  
The error I have only since the update to version 2.3.0

**Comment by klein0r** [comment]
The crontab for the weekly data is `0 0 * * 1`. So every monday at 00:00
Can you confirm that your systems date is correct?
Please share a log in debug mode when the instance has started.

**Comment by TomasiDeveloping** [comment]
Hello Matthias
Yes the system date is correct.
All custom cron are working. The problem also comes after the update. In TimeCount for example day and week is correct (see screenshot), only in SumDelta not.
![2023-04-06 16_51_00-objects - ioBroker](https://user-images.githubusercontent.com/67390491/230417636-5d5c9af3-94f6-4e22-b7ce-4b21bcb387f0.png)
[log.txt](https://github.com/iobroker-community-adapters/ioBroker.statistics/files/11171850/log.txt)

**Comment by TomasiDeveloping** [comment]
UPDATE:
The error must be in version 2.3. After the value for the week was set to 0 again on Friday I made a downgrade to version 2.2. Today Saturday the value of the week is correct.

**Comment by TomasiDeveloping** [comment]
Hello Matthias
I updated to version 2.4.0 last week.
Everything looks good again. On Monday the weekly value was the same as the daily value and today, Tuesday, it was not reset.
Looks like the bug is fixed in this version.
Thank you for your work.

**Comment by klein0r** [comment]
> Looks like the bug is fixed in this version.

Okay, please close the issue if it is fixed. I haven't tried to reproduce the issue right now.
