### ISSUE TITLE
Question: Is it possible to manually insert old data?

### ISSUE THREAD

**Issue by harvey637** [iobroker-community-adapters/ioBroker.statistics#212]
Hi,

I started with this adapter in the middle of a month. So day, month, quarter, year, ... start from the beginning of my enabling this adapter for a specific datasource.

If I know the old values from the start_of_day, start_of_month, start_of_quarter, start_of_year, .... 
can I add this MANUALLY once to some datapoints, so the current timeslice is correct from now on?

This is not about recalculation of old temporary values, but only to get the "last" timeslice (THIS day, THIS month, THIS year correct in sync with the ongoining new data.

Example: 
my heatpump consumption was "1000" (kWh) on "1.1.2023", "1400" on "1.11.2023", "1430" on "00:00 13.11.2023".
Now I have the hourly values from today correct from the enabling of the statistics for this datasource (I dont care about wrong hours, as this will be correct tommorow), but day/month/quarter/year are only reflecting changes from today.

Any info is helpfull!

Into the .saved. structure? In the .temp. structure.? what todo than? wait for hour/day/month/year rotation?
Can I start this manually after inserting data for one datasource?

Thank You
Harvey

**Comment by harvey637** [comment]
Hi Bot,
thank you for your auto answer:
1) it is not in the documentation
2) where is a beta version?
3) no logs are involved
4) it is a question, not an issue, so nobody talked about this
cu
Harvey

**Comment by klein0r** [comment]
> can I add this MANUALLY once to some datapoints, so the current timeslice is correct from now on?

Yes, but you have to stop the statistics instance before you change anything. Everything is stored in state values - so if you change something, the new state values will be used for calculation.
