### ISSUE TITLE
MinMaxWerte nicht korrekt

### ISSUE THREAD

**Issue by franks06347** [iobroker-community-adapters/ioBroker.statistics#215]
Hallo Matthias,
ich habe die Version v2.3.0 im Einsatz und für einen Datenpunkt die Statisics aktiviert:
![grafik](https://github.com/iobroker-community-adapters/ioBroker.statistics/assets/95623262/9bfd41f2-fe11-4f7b-aa12-96d70ae946d7)
Die Werte des Datenpunkts ändern sich permanent:
![grafik](https://github.com/iobroker-community-adapters/ioBroker.statistics/assets/95623262/d0198ec2-405e-4ed8-b08b-889cf26d80b9)
Die Werte, die der Adapter berechnet, passen nicht:
![grafik](https://github.com/iobroker-community-adapters/ioBroker.statistics/assets/95623262/40d9bd95-ec0f-4511-8cfa-087148292334)
Gruß
Frank

**Comment by klein0r** [comment]
Die Werte in `*.save.*` werden erst nach Tageswechsel / Monatswechsel usw. übernommen. Bis der entsprechende Zeitraum "um" ist, werden diese in `*.temp.*` gehalten. Wenn also die Daten von "heute" im Graphen verglichen werden, liegen die Daten von heute erstmal in `*.temp.*` (bis der Tag um ist).

Bitte auch davon einen Screenshot liefern.

**Comment by franks06347** [comment]
In Temp sieht es auch so aus:

![grafik](https://github.com/iobroker-community-adapters/ioBroker.statistics/assets/95623262/889a5ead-f2a2-483f-a3d2-e290799987b1)

**Comment by franks06347** [comment]
falls du logs oder weitere Daten für die Analyse brauchst ... bitte Bescheid geben.

**Comment by klein0r** [comment]
Ein Log auf Debug Loglevel hilft natürlich immer enorm. Ich hatte gehofft, dass es nur ein Verständnis-Problem ist. Scheint ja nicht so zu sein.

**Comment by franks06347** [comment]
Für die Datenpunkte 
EFHElektroGesamt
EFHElektroGesamt_o
sieht es gut aus.
aber beim Datenpunkt WolfWPCOP klappt es nicht:
![grafik](https://github.com/iobroker-community-adapters/ioBroker.statistics/assets/95623262/eb2ed2db-dd5e-45fd-9f54-af78d164eb48)

debug-log kommt gleich...

**Comment by franks06347** [comment]
[log_statistics.txt](https://github.com/iobroker-community-adapters/ioBroker.statistics/files/13437580/log_statistics.txt)

**Comment by klein0r** [comment]
Könnte es sein, dass Du deinen State nie mit "bestätigten" Werten beschreibst? Die werden nämlich vom Adapter ignoriert...

https://github.com/iobroker-community-adapters/ioBroker.statistics/blob/c106b793e02789cdd68fdac56c6431fc60ddfe1b/main.js#L375

**Comment by franks06347** [comment]
Oh je ... sorry,
der Fehler saß wieder vor der Tastatur,
ich hab es geändert:
![grafik](https://github.com/iobroker-community-adapters/ioBroker.statistics/assets/95623262/96b4ac78-c373-48a3-8e59-2a188ad032d6)
... und sofort klappts:
![grafik](https://github.com/iobroker-community-adapters/ioBroker.statistics/assets/95623262/5cf18d40-01d5-401d-9ae9-b007a29e050d)

man-oh-man
ich hab das in der Doku gelesen, aber meine Blockly's nicht geprüft.

Matthias, du hast einen gut!

Viele Grüße
Frank
