### ISSUE TITLE
Livewerte glätten

### ISSUE THREAD

**Issue by BenAhrdt** [iobroker-community-adapters/ioBroker.statistics#230]
Hallo, ich bin gerade daran einen Adapter zu entwickeln, mit dem man Signale glätten kann.
Unter anderem Mittelwert, lopwsd-Filter usw.
Mir wurde gesagt, dass diese Adapter das auch schon eventuell erschlägt.
Ist er dazu gemacht, oder bildet er quasi nur Mittelwerte für angegebene Zeiträume?

mich möchte Signale live filtern / glätten.

**Comment by klein0r** [comment]
Das ist eine Frage und kein Issue. Gerne das Forum nutzen.
