### ISSUE TITLE
[Bug]: Statistic Values are not updated

### ISSUE THREAD

**Issue by OlafWalther1969** [iobroker-community-adapters/ioBroker.statistics#245]
### I'm sure that

- [ ] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### The problem

Statistik Daten werden nicht aktualisiert.
Nur wenn ich den Datenpunkt manuell aktualisiere werden die Daten in den Statistic Adapter übernommen.
NodeJs und Js-Controller, IOB sind auf dem neuesten Stand. Statistik Adaper v.2.4.0
Die IoBroker Installation ist erst frisch aufgesetzt.

In den Logs gibt es keine Fehler

Ich habe mehrere Iobroker Installationen wo der Statistic Adapter funktioniert.
Das sind ältere Versionen vom nodes.js. etc drauf.

Hat vielleicht Jemand eine Idee?

*******************************************

Statistics data is not updated.
Only if I update the data point manually is the data transferred to the Statistic Adapter.
NodeJs and Js Controller, IOB are up to date. Statistics Adaper v.2.4.0
The IoBroker installation has just been set up.

I have several Iobroker installations where the Statistic Adapter works.
These are older versions of nodes.js. etc on it.

Maybe someone has an idea?

Thanks!

### Version of nodejs

16.20.2

### Version of ioBroker js-controller

5.0.19

### Version of adapter

v2.4.0

**Comment by klein0r** [comment]
Log?

**Comment by OlafWalther1969** [comment]
Guten Morgen Mathias,

ich hoffe das LOG reicht, bzw. es ist das Richtige?

LG

![Log Statistic](https://github.com/iobroker-community-adapters/ioBroker.statistics/assets/66950616/b5aa8604-b2fe-4d02-9592-0502dce2d496)
