### ISSUE TITLE
only first 4 names of devices are shown, all the others are not displayed

### ISSUE THREAD

**Issue by Qlink84** [iobroker-community-adapters/ioBroker.statistics#25]
![image](https://user-images.githubusercontent.com/15886027/60329195-27961b80-9990-11e9-8037-bd439a0d72d0.png)

**Comment by foxthefox** [comment]
What do you mean with "first 4 names"?
hm-rega - 0 - 30165 -> is 3 stages in the object tree
"save values for Pooltemperatur"  is the name of the datapoint whereby "save values for" comes from the adapter and "Pooltemperatur" from the logged value defined in the other adapter -> one name with 4 words
If the width of the name column would be too short, the "..." would indicate the not shown text.
The adapter takes over the information provided in the orignal datapoint, no adjustments.

may be you could indicate your problem more precisely.

**Comment by Qlink84** [comment]
sorry for the confusion. with first 4 names i mean "Pooltemperatur", "Schlafzimmertemperatur", "Schlafzimmerfeuchtigkeit" and "DutyCycle"
all following datapoint names are missing. width of the name column is much longer as needed.
for example datapoint 49599 is named w_temperatur, but w_temperatur is not showing up in statistics objects... 
![image](https://user-images.githubusercontent.com/15886027/60411865-1f77ef00-9bcf-11e9-9a10-99a594c5fe5a.png)

maybe it's because of the underscore in the name ?
