### ISSUE TITLE
[Feature Request]: Please consider to copy "descr" and "units" from the originating object into new created ones in save and temp

### ISSUE THREAD

**Issue by harvey637** [iobroker-community-adapters/ioBroker.statistics#279]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### The problem

This is a feature request.
When a statistics object is added a lot of new objects are created, e.g. a tree under "save" and under "temp" with lots of time spans like "hour", "day", "month" and so on, around 18 new objects.
All this objects do not contain the "desc" nor the "units" field of the originating.

But this inforrmation is easy fetchable and very informative for the new objects and especially for using timed delta in echarts.

Or I have to copy all this information manually to the used statistics objects or in all charts related to this objects, lot of unneccessary work!

### Version of nodejs

18.20.4

### Version of ioBroker js-controller

6.0.11

### Version of adapter

2.4.0

**Comment by mcm1957** [comment]
duplicate #213

**Comment by meisterschatten** [comment]
Agree!
Will be nice, to have the units from the root-object too.

**Comment by klein0r** [comment]
Added unit in 3.1.0
