### ISSUE TITLE
SumGroup states rounded always to 0 by state change 0.00009 for example kW/h in €

### ISSUE THREAD

**Issue by smartboart** [iobroker-community-adapters/ioBroker.statistics#28]
ok, the prblem is the 0.45 € per kw/h.. rounding or bette the value is to smallfor calculation...saw it in the debug log... is that practical? I mean no problem i let then calculate in cent instedd of €...but € and kw/h is a standart value....for this example the new rounding of values is not realy suitable.. I will close this issue

_Originally posted by @smartboart in https://github.com/foxthefox/ioBroker.statistics/issues/27#issuecomment-544121735_

**Comment by smartboart** [comment]
There is a Problem with SumGroup Values since V0.2.1. For example € pro kw/h in the last 15min or last hour  always roundet to 0 € because of state changes like 0,00008kw/h to 0,00009kw/h result is always 0.
Is there a chance to get this done like in Version 0.2.0 where it worked perfect?

**Comment by smartboart** [comment]
statistics.0 | 2019-10-19 20:13:59.198 | debug | (11706) [STATE CHANGE] Increase temp.sumGroup.energy.15Min on 0.31000000000676664 to 0
-- | -- | -- | --

**Comment by pdbjjens** [comment]
I second @smartboart 's request to improve the rounding of the sum values. I suggest that the rounding should be specified in the adapter's config tab under the label Preis/price. e.g. price = 1.000 should mean that the resultant value should be rounded to 3 digits after the colon. price= 1 should mean rounding to integer.
