### ISSUE TITLE
[Bug]: Statistics not working on (alias) objects updated by Script-Blockly-BindObject

### ISSUE THREAD

**Issue by bergteam** [iobroker-community-adapters/ioBroker.statistics#297]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### The problem

UseCase: I would like to have statistics for energy on a central place in 0_userdata. The location will now stay the same, if e.g. the zwave device name changes.

Steps:
1. Create new Object in 0_userdata
2. Enable Statistics on this object
3. Update object with blockly script
    a) by ObjectTrigger + Aktualisiere => This works
    b) by BindeObject => ***This does not work*** The statistic values remain empty.

![BindeObjekt](https://github.com/user-attachments/assets/a9d1f507-b4de-4959-9539-2c9a01308014)

This discussion concludes that "Binde Objekt" sets the object without the ack flag.
https://forum.iobroker.net/topic/70506/fage-zu-binde-objekt

=> Could it be changed that objects updated with BindeObject also work with the Statistics Adapter?

### Version of nodejs

v20.18.1

### Version of ioBroker js-controller

 7.0.6

### Version of adapter

3.1.0

**Comment by klein0r** [comment]
Bind = Trigger + Control (setState without ack).

You have to acknowledge (ack: true) the new value for your custom state. Not an issue.

https://github.com/iobroker-community-adapters/ioBroker.statistics/blob/0fda85ee922b681e2f02bf89103078a436767b62/docs/en/README.md?plain=1#L7
