### ISSUE TITLE
Statistic over time

### ISSUE THREAD

**Issue by sissiwup** [iobroker-community-adapters/ioBroker.statistics#32]
Hallo,

es wäre schön, wenn der Adapter den Verbrauch pro Monat / Tag/Woche/ Stunde / 1/4 Stunde
korrekt berechnen würde.
z.B. Verbrauch pro Stunde 17:00:-18:00
Messwerte: 16:57 100, Messwert 17:05 105
Berechneter Wert für 17:00 ca. 103 (je nach Interpolation).
Messwerte: 17:30 110
Messwert: 18.30 130
Berechneter Wert für 18:00 120
=> Verbrauch pro h 15

**Comment by foxthefox** [comment]
Um dein Beispiel nachzuvollziehen, wäre eine Angabe zu der gemachten Einstellung und über den Datenpunkt selbst recht hilfreich.

In deinem Beispiel gehe ich von einem stetig ansteigenden Wert aus. Dort soll dann die Differenz zwischen den Werten der Verbrauch darstellen. Der Adapter errechnet immer beim Eintreffen eines Messwertes die Differenz zum vorherigen und dies wird temporär gemerkt. Zum Log-Zeitpunkt wird dann die Summe der Verbräuche (Differenzen) dann im dafür vorgesehenen Datenpunkt abgelegt.

Interpolation oder nachträgliche Berechnung in Richtung Vergangenheit macht der Adapter nicht!
Er arbeitet ausschließlich mit den Messungen. Wo nichts gemessen wurde, wird auch nichts erraten. 

Bei wenig Messwerten ist natürlich klar, daß erst in einem größeren Betrachtungszeitraum z.B. Tag die Ermittlung hinreichend auswertbar ist. Evtl. kannst du ja die Datenquelle dazu bringen mehr Messwerte zu schicken.
