### ISSUE TITLE
Counting binary values in 1 minute intervals.

### ISSUE THREAD

**Issue by Aquasolar** [iobroker-community-adapters/ioBroker.statistics#36]
Would be helpful when used as a piece counter. In my case, the 5 minute interval is unfortunately not enough.

**Comment by foxthefox** [comment]
What is your use case? binary values and their changes are counted when they occur.

**Comment by Aquasolar** [comment]
Yes exactlyAm 20.02.2020 07:21 schrieb foxthefox <notifications@github.com>:What is your use case? binary values and their changes are counted when they occur.

**Comment by foxthefox** [comment]
What means "Yes exactly"?????
I have no glue what the problem is.

You can also write in German if it helps.
