### ISSUE TITLE
No reset of daily values

### ISSUE THREAD

**Issue by IoTWonderer** [iobroker-community-adapters/ioBroker.statistics#41]
In version 0.2.2 the daily values of temp are not reset at midnight; they continue to add...

**Comment by foxthefox** [comment]
that is strange, I need some more information
Are all temporary values not working?
Which configuration is particular causing this effect?

**Comment by IoTWonderer** [comment]
I cannot add a lot: I updated to 0.2.2 and after some days saw that the daily values do not update.
So I quickly downgraded to 0.2.1 and now it works fine again.
I can say that the effect occured in SumDelta datapoints...
