### ISSUE TITLE
Option to use SQL data for statistic

### ISSUE THREAD

**Issue by TeaJAge** [iobroker-community-adapters/ioBroker.statistics#44]
Do you think it is possible to use the existing SQL Data, selected like in the flot adapter.

The data is still there and does not have to be logged multiple times.
You only have to read the sql data and calculate the statistic objects.

**Comment by foxthefox** [comment]
In first moment I think, that it would be better to have a separate adapter for such application.
The focus here is to have values on defined times and not the calculation afterwards from sql.
