### ISSUE TITLE
No record of own datapoints 

### ISSUE THREAD

**Issue by DerRonX** [iobroker-community-adapters/ioBroker.statistics#49]
Meine eigenen Datenpunkte werden nur Mitternacht aktualisiert.

Datenpunkte wie z.B. rpi2.0.temperature.soc_temp oder tankerkoenig.0.stations.0.e5.short werden problemlos geloggt. Bei meinen eigenen Datenpunkte wird allerdings lediglich um Mitternacht der aktuelle Wert gespeichert.

Selbst bei Änderung erscheint im Log nur das:

`statistics.0	2020-07-12 22:40:01.490	debug	(1405) [STATE CHANGE] stateChange => 32 [false]
statistics.0	2020-07-12 22:40:01.490	debug	(1405) [STATE CHANGE] ======================= javascript.0.DatenPunkte.SNMP.QNAP1_SystemTemperature =======================
statistics.0	2020-07-12 22:40:01.386	debug	(1405) [STATE CHANGE] stateChange => 2 [false]
statistics.0	2020-07-12 22:40:01.385	debug	(1405) [STATE CHANGE] ======================= javascript.0.DatenPunkte.SNMP.QNAP1_CPU_Load =======================
statistics.0	2020-07-12 22:40:00.865	debug	(1405) [STATE CHANGE] stateChange => 76.4 [false]
statistics.0	2020-07-12 22:40:00.865	debug	(1405) [STATE CHANGE] ======================= javascript.0.DatenPunkte.SNMP.Router_SystemTemperature =======================
statistics.0	2020-07-12 22:40:00.758	debug	(1405) [STATE CHANGE] stateChange => 0 [false]
statistics.0	2020-07-12 22:40:00.757	debug	(1405) [STATE CHANGE] ======================= javascript.0.DatenPunkte.SNMP.Router_CPU_Load_1 =======================`

Der Zähler (dayCount) bleibt auf 0.

Einstellungen: Min/Max und Average

Installierte Version 0.2.2

**Comment by obiwan007** [comment]
You have to setState with ack = true. Then the value will be processed.
