### ISSUE TITLE
1.0.1 continuously warning [STATE CHANGE] wrong value

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.statistics#52]
After update from 0.2.2 to 1.0.1 I get never ending warnings in log from different devices/adapters.
`statistics.0	2020-12-22 22:49:16.653	warn	(2102229) [STATE CHANGE] wrong value => false on yeelight-2.0.Xiaomi-Yeelight-Bedside-Lamp2.control.power => check the other adapter where value comes from`
`statistics.0	2020-12-22 22:49:15.392	warn	(2102229) [STATE CHANGE] wrong value => false on sonoff.0.DVES_1BB306.POWER => check the other adapter where value comes from`
`statistics.0	2020-12-22 22:49:11.662	warn	(2102229) [STATE CHANGE] wrong value => false on sonoff.0.DVES_541E97.POWER => check the other adapter where value comes from`
`statistics.0	2020-12-22 22:49:07.359	warn	(2102229) [STATE CHANGE] wrong value => false on sonoff.0.DVES_A513A1.POWER => check the other adapter where value comes from`
`statistics.0	2020-12-22 22:48:46.568	warn	(2102229) [STATE CHANGE] wrong value => false on sonoff.0.DVES_BEB376.POWER => check the other adapter where value comes from`

JS-Controller 3.1.6
NodeJS 12.20.0
npm 6.14.9

**Comment by foxthefox** [comment]
the only thing what was recently updated was the rounding to 4 digits.
but this was 1.0.0 to 0.2.2

**Comment by Diginix** [comment]
Strange. Ive done a rollback to 0.2.2 and all is fine again.
Maybe I'll try the update again tomorrow.

**Comment by fuchs-1978** [comment]
Same problem here:
STATE CHANGE] wrong value => false on sonoff.0.Gaszaehler.POWER2 => check the other adapter where value comes from
--

With 0.2.2 all is fine

**Comment by foxthefox** [comment]
no need to retry upgrade to 1.0.1, it will happen again.

The changed code in 1.0.0 is:
`
if( (state.val === null) || (state.val === undefined) || (state.val === NaN) ){

to 

if (!state.val && state.val !== 0) {

`
and throws the same message.
before it was checking for invalid only.
may be @GermanBluefox can say something

As I said before, the adapter does not count on negative edges, only 0->1. So from working it is right, from logging I have no opinion.

**Comment by passuff** [comment]
I have the same issue here with true/false logging. My log is spamed all over with it. Could we somehow turn it off or is a rollback the only solution currently?

**Comment by foxthefox** [comment]
you can roll back, if you want.

**Comment by massimo1971** [comment]
> Strange. Ive done a rollback to 0.2.2 and all is fine again.
> Maybe I'll try the update again tomorrow.
> 
> It is this settings for all devices:
> ![image](https://user-images.githubusercontent.com/39678667/102940665-1fe60300-44b1-11eb-98d0-04e5e153712e.png)

Same Problem here, I had to roll back to 0.2.2

**Comment by watcherkb** [comment]
I have the same issue and no values are count.

**Comment by Diginix** [comment]
Since no developer has fixed the issue in 1.x so far, it seems 0.2.2 is the only suitable version for many users.

**Comment by maeb3** [comment]
I can confirm what @foxthefox said in the post above:
I'm running version 1.0.2 with the line 
`if (!state.val && state.val !== 0) {` 
manually changed in the main.js back to the original one (from version 0.2.2). Running for some weeks now. No problems, everything works fine. Time count calculation is now correct again (was wrong before because adapter did not recognize 1->0 edges, so it's not only a logging issue but also wrong values for online-time/offline-time). 

Has anybody any ideas wether there might be negative impact when switching back to the old line of code?

**Comment by foxthefox** [comment]
this is solved with 1.0.4

**Comment by Diginix** [comment]
Updated yesterday from 0.2.2 to 1.0.4 without log entries so far. Seems to be solved. Thanks!

**Comment by Stefan-83** [comment]
Now I have the same issue 😒 
Version 1.0.9

**Comment by Stefan-83** [comment]
Please re-open

**Comment by Stefan-83** [comment]
Update: After I've downgraded to 1.0.4., it's working again.
Is there a known error in 1.0.9 (latest version)
