### ISSUE TITLE
a lot of no existing object warnings with js-controller 3.2

### ISSUE THREAD

**Issue by Garfonso** [iobroker-community-adapters/ioBroker.statistics#57]
For example:

```
2021-01-21 17:50:03.834  - warn: statistics.1 (7333) State "statistics.1.temp.avg.alias.0.gas.Counter.total.last" has no existing object, this might lead to an error in future versions
2021-01-21 17:50:03.834  - warn: statistics.1 (7333) State "statistics.1.temp.avg.alias.0.gas.Counter.total.dayCount" has no existing object, this might lead to an error in future versions
2021-01-21 17:50:03.835  - warn: statistics.1 (7333) State "statistics.1.temp.avg.alias.0.gas.Counter.total.daySum" has no existing object, this might lead to an error in future versions
2021-01-21 17:50:03.836  - warn: statistics.1 (7333) State "statistics.1.temp.avg.alias.0.gas.Counter.total.dayAvg" has no existing object, this might lead to an error in future versions
2021-01-21 17:50:03.843  - warn: statistics.1 (7333) State "statistics.1.temp.avg.alias.0.gas.Counter.power.last" has no existing object, this might lead to an error in future versions
2021-01-21 17:50:03.843  - warn: statistics.1 (7333) State "statistics.1.temp.avg.alias.0.gas.Counter.power.dayCount" has no existing object, this might lead to an error in future versions
2021-01-21 17:50:03.844  - warn: statistics.1 (7333) State "statistics.1.temp.avg.alias.0.gas.Counter.power.daySum" has no existing object, this might lead to an error in future versions
2021-01-21 17:50:03.844  - warn: statistics.1 (7333) State "statistics.1.temp.avg.alias.0.gas.Counter.power.dayAvg" has no existing object, this might lead to an error in future versions

```

Adapter version: 1.0.2

**Comment by lobomau76** [comment]
Same version, same problem here. I run the adapter now only with error log on.

**Comment by foxthefox** [comment]
this is probably again a problem of the new js-controller

**Comment by Apollon77** [comment]
no, most likely the adapter is issuuing a setState before the object was really created.
I know that most there is handled by that taskQueue ... so you need to check in depth what happens here

**Comment by foxthefox** [comment]
the last big refactoring was done by bluefox and probably it is the best to transfer the adapter to the community anyway

**Comment by micklafisch** [comment]
same problem for me. Is there any solution about the massive log entries?

**Comment by Qlink84** [comment]
same problem here ... adapter is flooding log since js controller upgrade... anyone working on this ?

**Comment by Qlink84** [comment]
have upgraded to v1.0.4 today... log entry flooding still happens:

e.g.

```
statistics.0 | 2021-04-29 08:09:16.918 | warn | (8556) State "statistics.0.temp.avg.stiebel-isg.0.Info.WAERMEPUMPE.WAERMEMENGE.WM_KUEHLEN_SUMME.dayCount" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
statistics.0 | 2021-04-29 08:09:16.918 | warn | (8556) State "statistics.0.temp.avg.stiebel-isg.0.Info.WAERMEPUMPE.WAERMEMENGE.WM_KUEHLEN_SUMME.last" has no existing object, this might lead to an error in future versions
statistics.0 | 2021-04-29 08:09:16.902 | warn | (8556) State "statistics.0.temp.avg.stiebel-isg.0.Info.WAERMEPUMPE.WAERMEMENGE.WM_WRG_SUMME.dayAvg" has no existing object, this might lead to an error in future versions

```

**Comment by foxthefox** [comment]
1.0.4 does not declare that this problem is solved.
to avoid the entries a refactoring is necessary, hence the js-controller is checking more in the recent versions.
I have donated the adapter to the community in the hope that my limited time is no longer the blocking point for enhancements

**Comment by AlexHaxe** [comment]
I got loads of these messages as well. 

I don't really know much about the whole ecosystem, but I wouldn't have thought js controller had anything to do with it.
for me it looks like statistics adapter tries to write / read a key that it neglected to create when enabling statistics on a value.
and no matter what I do it doesn't seem to ever create any of these, though I haven't tried to create them manually to see if it would shut up about it (probably).

so if statistics adapter wants to use those values why does it not check and create them? or why does it skip creating `avg` keys when it adds all the other keys just fine?

**Comment by CaneTLOTW** [comment]
I seem to have the same issue:

<html>
<body>


statistics.0 | 2021-07-07 22:33:12.269 | warn | (8205) State "statistics.0.temp.avg.javascript.0.Data.Fritz.NewTotalBytesReceived.TB.dayCount" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
statistics.0 | 2021-07-07 22:33:12.223 | warn | (8205) State "statistics.0.temp.avg.javascript.0.Data.Fritz.NewTotalBytesReceived.TB.last" has no existing object, this might lead to an error in future versions
statistics.0 | 2021-07-07 22:33:07.380 | warn | (8205) State "statistics.0.temp.avg.javascript.0.Data.Fritz.NewTotalBytesReceived.TB.dayAvg" has no existing object, this might lead to an error in future versions
statistics.0 | 2021-07-07 22:33:07.330 | warn | (8205) State "statistics.0.temp.avg.javascript.0.Data.Fritz.NewTotalBytesReceived.TB.daySum" has no existing object, this might lead to an error in future versions
statistics.0 | 2021-07-07 22:33:07.279 | warn | (8205) State "statistics.0.temp.avg.javascript.0.Data.Fritz.NewTotalBytesReceived.TB.dayCount" has no existing object, this might lead to an error in future versions
statistics.0 | 2021-07-07 22:33:07.230 | warn | (8205) State "statistics.0.temp.avg.javascript.0.Data.Fritz.NewTotalBytesReceived.TB.last" has no existing object, this might lead to an error in future versions


</body>
</html>

Is there anything new on this topic?

**Comment by Apollon77** [comment]
Ok, please anyone provide a full debug log. I need to see "where" in the flow the relevante mesages appear

**Comment by CaneTLOTW** [comment]
@Apollon77 
How do i do a full debug log?

**Comment by Apollon77** [comment]
Best use the GitHub version for this test ( restart manually after install from GitHub)

**Comment by Apollon77** [comment]
@CaneTLOTW In admin enable expert mode then change the loglevel of the instance to "debug". Then best get the log from logfile on disk (/opt/iobroker/log/...) and not from admin

**Comment by CaneTLOTW** [comment]
I did not do the reinstall from GitHub (for now), no time to fix the system in general...
Switched to debug and will collect a bit of log file for you.

**Comment by CaneTLOTW** [comment]
@Apollon77 

Should contain a couple of events with warning
[iobroker.2021-07-13.log](https://github.com/iobroker-community-adapters/ioBroker.statistics/files/6804722/iobroker.2021-07-13.log)

If you need more if will keep logging on debug for a little while.

**Comment by Apollon77** [comment]
> What is the differnce between this and git version?

The adapter already subscribed to data and started work processes before initialization was done, so Ichanged that to start AFTER init was done ...

**Comment by CaneTLOTW** [comment]
I see, how to switch to GIT version?

**Comment by Apollon77** [comment]
Ok, that helped. I found a case where in theory object creations are blocked and so not finally processed. Please install GitHub version and try again. please provide log if still an issue

**Comment by Apollon77** [comment]
> I see, how to switch to GIT version?

In Admin there is a github symbol in export mdoe I think where you can do a"custom install". just chose this adapter fromthe selection and you instakl the github version. Then do a manual restart after install

**Comment by CaneTLOTW** [comment]
Thanks!

will test tonight and report back!

**Comment by Apollon77** [comment]
Output are the usual warnings vrfrom npm for szuff ... all good

**Comment by CaneTLOTW** [comment]
@Apollon77 

Still this:
<html><body>


statistics.0 | 2021-07-13 16:30:53.491 | warn | (18909)  State  "statistics.0.temp.avg.hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER.daySum" has  no existing object, this might lead to an error in future versions
-- | -- | -- | --
statistics.0 | 2021-07-13 16:30:53.440 | warn | (18909)  State  "statistics.0.temp.avg.hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER.dayCount"  has no existing object, this might lead to an error in future versions
statistics.0 | 2021-07-13 16:30:53.381 | warn | (18909)  State "statistics.0.temp.avg.hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER.last"  has no existing object, this might lead to an error in future versions
statistics.0 | 2021-07-13 16:30:53.378 | debug | (18909) [STATE CHANGE] new last for "temp.avg.hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER.last: 26.7
statistics.0 | 2021-07-13 16:30:53.371 | debug | (18909) [STATE CHANGE] Increase temp.sumDelta.hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER.year on 26.7 to 4358919.9024
statistics.0 | 2021-07-13 16:30:53.361 | debug | (18909) [STATE CHANGE] Increase temp.sumDelta.hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER.quarter on 26.7 to 2007546.6016
statistics.0 | 2021-07-13 16:30:53.350 | debug | (18909) [STATE CHANGE] Increase temp.sumDelta.hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER.month on 26.7 to 711813.4008
statistics.0 | 2021-07-13 16:30:53.344 | debug | (18909) [STATE CHANGE] Increase temp.sumDelta.hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER.week on 26.7 to 22720
statistics.0 | 2021-07-13 16:30:53.336 | debug | (18909) [STATE CHANGE] Increase temp.sumDelta.hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER.day on 26.7 to 9200
statistics.0 | 2021-07-13 16:30:53.329 | debug | (18909) [STATE CHANGE] Increase temp.sumDelta.hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER.hour on 26.7 to 480
statistics.0 | 2021-07-13 16:30:53.314 | debug | (18909) [STATE CHANGE] Increase temp.sumDelta.hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER.15Min on 26.7 to 26.7
statistics.0 | 2021-07-13 16:30:53.297 | debug | (18909) [STATE CHANGE] avg call: hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER value 26.7
statistics.0 | 2021-07-13 16:30:53.297 | debug | (18909) [STATE CHANGE] stateChange => 350573.3 [true]
statistics.0 | 2021-07-13 16:30:53.296 | debug | (18909) [STATE CHANGE] ======================= hm-rpc.0.PEQ0544431.1.ENERGY_COUNTER =======================


</body>
</html>

Anything I have to do? After install I stopped and started statistics

**Comment by Apollon77** [comment]
Then full debaug log please again as before

**Comment by CaneTLOTW** [comment]
Update was around 16:15
[iobroker.2021-07-13.log](https://github.com/iobroker-community-adapters/ioBroker.statistics/files/6809653/iobroker.2021-07-13.log)

**Comment by Apollon77** [comment]
Der Adapter restart (nach Update) war dann 16:27??

**Comment by CaneTLOTW** [comment]
Ja, das müsste passen. hatte vergessen Ihn vor dem Update zu stoppen.

Habe Ihn dann gestoppt, nochmal den install laufen lassen und dann gestartet.

**Comment by Apollon77** [comment]
@GermanBluefox Hm ... here I need a logic advice.

Code in https://github.com/iobroker-community-adapters/ioBroker.statistics/blob/master/main.js#L1402 handled the case `(obj.avg && !obj.sumDelta)` ... and create the "avg" objects. Some lines down we have the code handling `(obj.sumDelta)` but this is not creatung the avg objects. means in fact that they are missing because no code handles the `(obj.avg && obj.sumDelta)`. case - and the log shows exactly such a configured object.

Because I'm not that deep in the internals ... whats the change needed?

**Comment by CaneTLOTW** [comment]
Any news on this?

**Comment by GermanBluefox** [comment]
Please test 1.0.8

**Comment by Apollon77** [comment]
@CaneTLOTW Can oyu please try it? I personally do not expect to be ficed because the avg objects should still not be created, but maybe I was looking wrong.

In this case sumDelta AND avg are true ... and in https://github.com/iobroker-community-adapters/ioBroker.statistics/blob/master/main.js#L1366 there should be still no logic to create avg states for this case because https://github.com/iobroker-community-adapters/ioBroker.statistics/blob/master/main.js#L1407 is not executed

**Comment by CaneTLOTW** [comment]
Hi,

1st of all thanks a lot for the help here :)

No warning in log so far. I will keep an eye on it and report back again in the morning.
But it seems to be fixed :)

**Comment by Apollon77** [comment]
Cool, then we close here
