### ISSUE TITLE
State value to set

### ISSUE THREAD

**Issue by Matt77CHE** [iobroker-community-adapters/ioBroker.statistics#71]
Hallo
mir wird im Moment das Log mit state value to set -Meldungen überhäuft:

> 

tate  value to set for  "statistics.0.temp.timeCount.sonoff.0.GV_03.POWER.last" has to be type  "number" but received type "boolean"
--
statistics.0 | 2021-05-31 18:22:33.048 | info | State  value to set for  "statistics.0.temp.timeCount.sonoff.0.GV_02.POWER.last" has to be type  "number" but received type "boolean"
statistics.0 | 2021-05-31 18:22:32.987 | info | State  value to set for  "statistics.0.temp.timeCount.sonoff.0.GV_05.POWER.last" has to be type  "number" but received type "boolean"
statistics.0 | 2021-05-31 18:22:32.980 | info | State  value to set for  "statistics.0.temp.timeCount.sonoff.0.GV_03.POWER.last" has to be type  "number" but received type "boolean

.. und das mit nicht sehr wenigen Meldungen...
Habe laae Adapter, Admin etc auf aktuellem Stand.

**Comment by GermanBluefox** [comment]
Statistics funktioniert nur mit "number". Du versuchst aber "POWER" - "boolean" zu benutzen

**Comment by Matt77CHE** [comment]
Ok, naja ich dachte, dass true / false auch erkannt wird - nicht "nur"  0/1...
Mal schauen, ob ich das irgendwie hinkriege, sonst muss ich eine andere Lösung als Statistics suchen

Danke für die Rückmeldung
