### ISSUE TITLE
Update unter Windows Fehler

### ISSUE THREAD

**Issue by Burgruine** [iobroker-community-adapters/ioBroker.statistics#72]
Beim update unter Windows kommt folgende Fehlermeldung: 

`$ iobroker upgrade statistics@1.0.6

Update statistics from @1.0.4 to @1.0.6

NPM version: 6.14.10

npm install iobroker.statistics@1.0.6 --loglevel error (System call)

npm ERR! code EBUSY

npm ERR! syscall rename npm ERR! path C:\iobroker\node_modules\iobroker.statistics npm ERR! dest C:\iobroker\node_modules\.iobroker.statistics.DELETE npm ERR! errno -4082

npm ERR! EBUSY: resource busy or locked, rename 'C:\iobroker\node_modules\iobroker.statistics' -> 'C:\iobroker\node_modules\.iobroker.statistics.DELETE'

npm ERR! A complete log of this run can be found in: npm ERR! C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2021-06-03T14_20_54_187Z-debug.log

host.NUC Cannot install iobroker.statistics@1.0.6: 4294963214

ERROR: Process exited with code 25`

**Comment by Apollon77** [comment]
please end adapter and try again to update
